#!/bin/bash
# ============================================================================
# Confidential Intents E2E Test — coordinator /wallet/v1/confidential/* routes
#
# Real-token end-to-end test of the confidential shard (Defuse confidential
# intents) THROUGH the coordinator, the confidential analog of
# wallet_intents_e2e.sh. Mirrors the live exploration scripts
# (/tmp/conf_e2e.py shield+withdraw, conf_solana.py cross-chain deposit,
# conf_sol_out.py cross-chain withdraw) but drives the coordinator REST API and
# asserts on settlement + confidential balance deltas.
#
# Phases:
#   setup           — register wallet OR reuse saved state.env; show address + prereqs
#   roundtrip       — SHIELD 0.01 wNEAR → assert settled + balance +amount →
#                     UNSHIELD → assert settled + balance back. THE real-token test.
#   shield          — SHIELD only (asserts settlement)
#   unshield        — UNSHIELD only (asserts settlement)
#   balance         — show confidential balances
#   deposit-intent  — cross-chain DEPOSIT quote (Solana → confidential; address only)
#   withdraw        — cross-chain WITHDRAW (asserts settlement)
#   status <id>     — poll a request to terminal status
#   show / reset    — print / nuke saved wallet state
#
# GATE: the live phases require ONECLICK_CONFIDENTIAL_JWT to be set;
# unset → SKIP (exit 0), so CI can run this unconditionally. The coordinator must
# also have ENABLE_CONFIDENTIAL_INTENTS + the confidential upstream configured
# (else routes return HTTP 503, which the script surfaces).
#
# PREREQ for roundtrip/shield: the wallet must already hold SHIELD_AMOUNT of
# SHIELD_TOKEN in its PUBLIC intents balance. Fund it first, e.g. via
# wallet_intents_e2e.sh (fund NEAR → wrap → POST /wallet/v1/intents/deposit).
#
# Usage:
#   ./tests/wallet_confidential_e2e.sh setup
#   ONECLICK_CONFIDENTIAL_JWT=1 ./tests/wallet_confidential_e2e.sh roundtrip
#   ONECLICK_CONFIDENTIAL_JWT=1 WITHDRAW_CHAIN=solana \
#     WITHDRAW_TO=<sol-addr> WITHDRAW_TOKEN=nep141:sol-…omft.near WITHDRAW_AMOUNT=500000 \
#     ./tests/wallet_confidential_e2e.sh withdraw
#
# Environment:
#   COORDINATOR_URL  — default http://localhost:8080
#   NETWORK          — testnet | mainnet (default: mainnet; confidential talks to mainnet intents.near)
#   WALLET_API_KEY   — override saved key (usually let setup save it)
#   SHIELD_TOKEN     — default nep141:wrap.near
#   SHIELD_AMOUNT    — default 10000000000000000000000 (0.01 wNEAR, 24 dec)
#   WITHDRAW_CHAIN   — destination chain (default: solana); chain=near is rejected (use unshield)
#   WITHDRAW_TO      — destination-chain recipient address
#   WITHDRAW_TOKEN   — confidential source asset to deliver (e.g. nep141:sol-…omft.near)
#   WITHDRAW_AMOUNT  — amount in minimal units
#   DEPOSIT_SOURCE_ASSET — defuse asset id to bridge in (default: Solana USDC omft)
#   DEPOSIT_AMOUNT   — amount in minimal units (default: 500000 = 0.5 USDC)
# ============================================================================

set -euo pipefail

COORDINATOR_URL="${COORDINATOR_URL:-http://localhost:8080}"
NETWORK="${NETWORK:-mainnet}"

SHIELD_TOKEN="${SHIELD_TOKEN:-nep141:wrap.near}"
SHIELD_AMOUNT="${SHIELD_AMOUNT:-10000000000000000000000}" # 0.01 wNEAR (24 decimals)

SOL_USDC="nep141:sol-5ce3bf3a31af18be40ba30f721101b4341690186.omft.near"
DEPOSIT_SOURCE_ASSET="${DEPOSIT_SOURCE_ASSET:-$SOL_USDC}"
DEPOSIT_AMOUNT="${DEPOSIT_AMOUNT:-500000}" # 0.5 USDC (6 decimals)

# ─── State persistence (shared convention with wallet_intents_e2e.sh) ────────
STATE_DIR="${OUTLAYER_E2E_STATE_DIR:-$HOME/.outlayer}"
STATE_FILE="${OUTLAYER_E2E_STATE_FILE:-$STATE_DIR/wallet_e2e_state.env}"

if [ -z "${WALLET_API_KEY:-}" ] && [ -f "$STATE_FILE" ]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    if [ -n "${WALLET_API_KEY:-}" ]; then
        echo "↻ loaded saved wallet from $STATE_FILE (wallet_id=${WALLET_ID:-?}, account=${NEAR_ADDRESS:-?})"
    fi
fi

save_state() {
    mkdir -p "$STATE_DIR"
    umask 077
    {
        echo "# Generated by wallet_confidential_e2e.sh / wallet_intents_e2e.sh setup — do not commit."
        echo "WALLET_API_KEY=${WALLET_API_KEY}"
        echo "WALLET_ID=${WALLET_ID:-}"
        echo "NEAR_ADDRESS=${NEAR_ADDRESS:-}"
        echo "COORDINATOR_URL=${COORDINATOR_URL}"
        echo "NETWORK=${NETWORK}"
        echo "SAVED_AT=$(date -u +%FT%TZ)"
    } > "$STATE_FILE"
    chmod 600 "$STATE_FILE"
}

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'; NC='\033[0m'

# ============================================================================
# Helpers
# ============================================================================

curl_get() {
    curl -s -w "\n%{http_code}" -H "Authorization: Bearer $WALLET_API_KEY" "${COORDINATOR_URL}${1}"
}

curl_post() {
    local path="$1" body="$2" idem_key="${3:-}"
    local extra_headers=()
    [ -n "$idem_key" ] && extra_headers+=(-H "X-Idempotency-Key: $idem_key")
    curl -s -w "\n%{http_code}" -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $WALLET_API_KEY" \
        ${extra_headers[@]+"${extra_headers[@]}"} \
        -d "$body" "${COORDINATOR_URL}${path}"
}

parse_response() {
    RESP_BODY=$(echo "$1" | sed '$d')
    RESP_CODE=$(echo "$1" | tail -1)
}

check_coordinator() {
    if ! curl -s "${COORDINATOR_URL}/health" > /dev/null 2>&1; then
        echo -e "${RED}ERROR: Coordinator not running at ${COORDINATOR_URL}${NC}"; exit 1
    fi
}

require_confidential_enabled() {
    if [ -z "${ONECLICK_CONFIDENTIAL_JWT:-}" ]; then
        echo -e "${YELLOW}SKIP:${NC} ONECLICK_CONFIDENTIAL_JWT is not set — confidential e2e disabled."
        echo "      Set it (any value) to run the live confidential phases; the coordinator must"
        echo "      also have ENABLE_CONFIDENTIAL_INTENTS + the confidential upstream configured."
        exit 0
    fi
}

require_api_key() {
    WALLET_API_KEY="${WALLET_API_KEY:?No wallet API key — run '$0 setup' first (or set WALLET_API_KEY).}"
}

# Big-integer compare (24-dec amounts exceed bash/64-bit). Echoes -1 | 0 | 1.
bi_cmp() { python3 -c "import sys;a=int(sys.argv[1]);b=int(sys.argv[2]);print(0 if a==b else(1 if a>b else -1))" "$1" "$2"; }
bi_add() { python3 -c "import sys;print(int(sys.argv[1])+int(sys.argv[2]))" "$1" "$2"; }

# Confidential balance of one token ("0" if absent). Echoes the integer string.
cf_balance() {
    local token="$1" resp
    resp=$(curl_get "/wallet/v1/confidential/balance?token=$(printf '%s' "$token" | sed 's/:/%3A/g')")
    parse_response "$resp"
    [ "$RESP_CODE" = "200" ] || { echo -e "${RED}cf_balance HTTP $RESP_CODE: $RESP_BODY${NC}" >&2; return 1; }
    echo "$RESP_BODY" | jq -r '.balance // "0"'
}

# Public intents balance of one token (for the shield prereq). Echoes the integer.
public_intents_balance() {
    local token="$1" resp
    resp=$(curl_get "/wallet/v1/balance?source=intents&token=$(printf '%s' "$token" | sed 's/:/%3A/g')")
    parse_response "$resp"
    [ "$RESP_CODE" = "200" ] || { echo "0"; return 0; }
    echo "$RESP_BODY" | jq -r '.balance // "0"'
}

# Submit a confidential op; sets LAST_REQUEST_ID; hard-fails on non-200 / 503.
report_op() {
    echo -e "  HTTP $RESP_CODE"
    if [ "$RESP_CODE" = "503" ]; then
        echo -e "  ${YELLOW}503 confidential_unavailable${NC} — coordinator not configured for confidential intents."
        echo "  $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"; exit 1
    fi
    if [ "$RESP_CODE" != "200" ]; then
        echo -e "  ${RED}FAIL${NC}: $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"; exit 1
    fi
    echo "  $(echo "$RESP_BODY" | jq -c '.')"
    LAST_REQUEST_ID=$(echo "$RESP_BODY" | jq -r '.request_id // empty')
}

# Poll a request to terminal. Returns 0=success, 1=failed/refunded, 2=timeout.
#
# Bumped from 30 to 90 iterations (= ~3 min wall-clock) because UNSHIELD
# direction reliably moves the funds on-chain in seconds but its upstream
# /v0/status sometimes stays "processing" for >60 s before flipping to
# "success" — the solver fills `nearTxHashes` lazily for the unshield leg.
# Most ops settle in < 15 iterations; the headroom protects against the slow
# UNSHIELD path without slowing the fast ones.
poll_request() {
    local rid="$1" i status
    [ -n "$rid" ] || { echo -e "  ${YELLOW}no request_id to poll${NC}"; return 2; }
    echo -e "${CYAN}  polling request $rid …${NC}"
    for i in $(seq 1 90); do
        parse_response "$(curl_get "/wallet/v1/requests/$rid")"
        status=$(echo "$RESP_BODY" | jq -r '.status // "?"')
        echo "    [$i] status=$status"
        case "$status" in
            success) echo "    $(echo "$RESP_BODY" | jq -c '.result')"; return 0 ;;
            failed|refunded) echo -e "    ${RED}terminal: $status${NC} $(echo "$RESP_BODY" | jq -c '.result')"; return 1 ;;
        esac
        sleep 2
    done
    return 2
}

# Poll + hard-assert the op settled to success.
assert_settled() {
    local rid="$1" label="$2" rc
    set +e; poll_request "$rid"; rc=$?; set -e
    case "$rc" in
        0) echo -e "  ${GREEN}PASS${NC} $label settled (success)" ;;
        1) echo -e "  ${RED}FAIL${NC} $label settled to a terminal failure"; exit 1 ;;
        2) echo -e "  ${RED}FAIL${NC} $label did not settle within timeout (rid=$rid; re-check via: $0 status $rid)"; exit 1 ;;
    esac
}

ensure_address() {
    if [ -z "${NEAR_ADDRESS:-}" ]; then
        parse_response "$(curl_get "/wallet/v1/address?chain=near")"
        [ "$RESP_CODE" = "200" ] || { echo -e "${RED}get address HTTP $RESP_CODE${NC}: $RESP_BODY"; exit 1; }
        NEAR_ADDRESS=$(echo "$RESP_BODY" | jq -r '.address')
    fi
}

# ============================================================================
# Commands
# ============================================================================

cmd_setup() {
    echo -e "${CYAN}== Confidential E2E — Setup (network: $NETWORK) ==${NC}"
    check_coordinator
    if [ -z "${WALLET_API_KEY:-}" ]; then
        echo "Registering new wallet…"
        parse_response "$(curl -s -w "\n%{http_code}" -X POST "${COORDINATOR_URL}/register")"
        [ "$RESP_CODE" = "200" ] || { echo -e "${RED}register HTTP $RESP_CODE${NC}: $RESP_BODY"; exit 1; }
        WALLET_API_KEY=$(echo "$RESP_BODY" | jq -r '.api_key')
        WALLET_ID=$(echo "$RESP_BODY" | jq -r '.wallet_id')
        NEAR_ADDRESS=$(echo "$RESP_BODY" | jq -r '.near_account_id')
        save_state
        echo -e "Saved state to $STATE_FILE (chmod 600)."
    fi
    ensure_address
    echo -e "Wallet ID:    ${GREEN}${WALLET_ID:-?}${NC}"
    echo -e "NEAR address: ${GREEN}$NEAR_ADDRESS${NC}"
    echo ""
    echo "Prerequisite for roundtrip/shield:"
    echo "  $SHIELD_TOKEN must already be in your PUBLIC intents balance ≥ $SHIELD_AMOUNT."
    echo "  Fund via wallet_intents_e2e.sh: fund NEAR → wrap (/call) → POST /wallet/v1/intents/deposit."
}

# Self-contained real-token assertion: SHIELD then UNSHIELD, verifying balances.
cmd_roundtrip() {
    require_confidential_enabled
    require_api_key
    check_coordinator
    echo -e "${CYAN}== Confidential round-trip: SHIELD → UNSHIELD ($SHIELD_AMOUNT $SHIELD_TOKEN) ==${NC}"

    # Prereq: public intents balance must cover the shield amount.
    local pub_bal; pub_bal=$(public_intents_balance "$SHIELD_TOKEN")
    echo "  public intents balance of $SHIELD_TOKEN: $pub_bal"
    if [ "$(bi_cmp "$pub_bal" "$SHIELD_AMOUNT")" = "-1" ]; then
        echo -e "  ${RED}FAIL${NC}: need ≥ $SHIELD_AMOUNT in public intents to shield. Fund first (see 'setup')."
        exit 1
    fi

    local cf_before; cf_before=$(cf_balance "$SHIELD_TOKEN")
    echo "  confidential balance before: $cf_before"

    echo -e "${CYAN}[1/4] SHIELD…${NC}"
    # Body built in a variable to dodge bash brace-expansion inside `$(...)` which
    # otherwise splits `{"a":"X","b":"Y"}` into two function calls.
    local shield_body; shield_body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/deposit" "$shield_body" "shield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "SHIELD"

    echo -e "${CYAN}[2/4] verify confidential balance increased by $SHIELD_AMOUNT…${NC}"
    local cf_mid expected_mid; cf_mid=$(cf_balance "$SHIELD_TOKEN"); expected_mid=$(bi_add "$cf_before" "$SHIELD_AMOUNT")
    echo "  confidential balance after shield: $cf_mid (expected $expected_mid)"
    if [ "$(bi_cmp "$cf_mid" "$expected_mid")" = "0" ]; then
        echo -e "  ${GREEN}PASS${NC} balance increased by the shielded amount"
    else
        echo -e "  ${YELLOW}WARN${NC} balance != before+amount (fees/rounding or solver timing); continuing"
    fi

    echo -e "${CYAN}[3/4] UNSHIELD…${NC}"
    local unshield_body; unshield_body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/unshield" "$unshield_body" "unshield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "UNSHIELD"

    echo -e "${CYAN}[4/4] verify confidential balance returned to baseline…${NC}"
    local cf_after; cf_after=$(cf_balance "$SHIELD_TOKEN")
    echo "  confidential balance after unshield: $cf_after (baseline $cf_before)"
    if [ "$(bi_cmp "$cf_after" "$cf_before")" = "0" ]; then
        echo -e "  ${GREEN}PASS${NC} round-trip complete — balance back to baseline"
    else
        echo -e "  ${YELLOW}WARN${NC} residual delta (fees/rounding/timing): after=$cf_after baseline=$cf_before"
    fi
    echo -e "${GREEN}round-trip OK${NC}"
}

cmd_shield() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== SHIELD $SHIELD_AMOUNT of $SHIELD_TOKEN ==${NC}"
    local body; body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/deposit" "$body" "shield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "SHIELD"
}

cmd_unshield() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== UNSHIELD $SHIELD_AMOUNT of $SHIELD_TOKEN ==${NC}"
    local body; body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/unshield" "$body" "unshield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "UNSHIELD"
}

cmd_balance() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== Confidential balances ==${NC}"
    parse_response "$(curl_get "/wallet/v1/confidential/balance")"
    echo -e "  HTTP $RESP_CODE"
    echo "  $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"
    [ "$RESP_CODE" = "200" ] || exit 1
}

cmd_deposit_intent() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== Cross-chain DEPOSIT intent (quote only): $DEPOSIT_SOURCE_ASSET → confidential ==${NC}"
    local body; body=$(printf '{"source_asset":"%s","amount":"%s"}' "$DEPOSIT_SOURCE_ASSET" "$DEPOSIT_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/deposit-intent" "$body")"
    echo -e "  HTTP $RESP_CODE"
    [ "$RESP_CODE" = "200" ] || { echo "  $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"; exit 1; }
    echo "  $(echo "$RESP_BODY" | jq -c '.')"
    echo -e "  ${CYAN}Send $DEPOSIT_AMOUNT to deposit_address on the source chain to fund your confidential balance.${NC}"
}

cmd_withdraw() {
    require_confidential_enabled; require_api_key; check_coordinator
    local chain="${WITHDRAW_CHAIN:-solana}"
    local to="${WITHDRAW_TO:?Set WITHDRAW_TO=<destination-chain address>}"
    local token="${WITHDRAW_TOKEN:-$SOL_USDC}"
    local amount="${WITHDRAW_AMOUNT:-$DEPOSIT_AMOUNT}"
    echo -e "${CYAN}== WITHDRAW $amount $token (confidential → $chain:$to) ==${NC}"
    local body="{\"chain\":\"$chain\",\"to\":\"$to\",\"amount\":\"$amount\",\"token\":\"$token\"}"
    echo -e "${CYAN}[1/2] dry-run…${NC}"
    parse_response "$(curl_post "/wallet/v1/confidential/withdraw/dry-run" "$body")"
    echo -e "  HTTP $RESP_CODE : $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"
    echo -e "${CYAN}[2/2] real withdraw…${NC}"
    parse_response "$(curl_post "/wallet/v1/confidential/withdraw" "$body" "cwithdraw-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "WITHDRAW"
}

cmd_status() {
    require_api_key
    local rid="${1:-${LAST_REQUEST_ID:-}}"
    [ -n "$rid" ] || { echo -e "${RED}Usage: $0 status <request_id>${NC}"; exit 1; }
    set +e; poll_request "$rid"; local rc=$?; set -e
    [ "$rc" = "1" ] && exit 1 || true
}

cmd_show() {
    echo "State file: $STATE_FILE"
    echo "WALLET_ID:    ${WALLET_ID:-<none>}"
    echo "NEAR_ADDRESS: ${NEAR_ADDRESS:-<none>}"
    echo "API key:      ${WALLET_API_KEY:0:10}${WALLET_API_KEY:+…}"
}

cmd_reset() {
    if [ -f "$STATE_FILE" ]; then rm -f "$STATE_FILE"; echo "Removed $STATE_FILE."; else echo "No saved state at $STATE_FILE."; fi
}

# ============================================================================
# multisig — confidential Trusted op UNDER MULTISIG (MAINNET-only) [POLICY+SIG]
#
# The confidential multisig pending→approve→execute control flow CANNOT be
# exercised on testnet: /confidential/* returns HTTP 503 off-mainnet (the
# salt/shard live on mainnet intents.near), so unified_op_e2e.sh's T9/T10
# (swap/cross-chain under multisig) have no confidential analog there. This is
# that missing test — the confidential sibling of T9: a Trusted confidential op
# on a MULTISIG wallet must return `pending_approval` (NOT execute, NOT "no
# multisig support"), and after the approval threshold it must LEAVE
# pending_approval (the keystore re-derives request_hash from the canonical
# Op::Confidential and signs the approved artifact; the quote is re-fetched
# fresh at execution — see coordinator confidential::handlers::
# create_confidential_pending / execute_approved_confidential).
#
# We assert the CONTROL FLOW (pending_approval → approve → leaves
# pending_approval), NOT terminal swap settlement — the pending approval is
# created from the policy decision BEFORE any quote/balance work, so this needs
# NO funded confidential balance (mirrors T9c/T10c, which accept a downstream
# 'failed' as proof the op left pending_approval). Tiny amount.
#
# Self-contained bootstrap mirroring unified_op_e2e.sh (this file otherwise uses
# a random-register bearer key with no on-chain policy): deploy a MAINNET vault,
# derive a sub-wallet, store an on-chain policy with approval.threshold + the
# default-DENY `confidential` capability, then drive the same NEP-413 approver
# `vote` helper T9/T10 use: sign `approve:{approval_id}:{wallet_pubkey}:{request_hash}`
# and POST /wallet/v1/approve/{approval_id}.
#
# GATE: require_confidential_enabled (ONECLICK_CONFIDENTIAL_JWT) like every live
# phase, PLUS SKIP cleanly (exit 0) if NETWORK != mainnet or the multisig infra
# env is absent (PARENT logged into outlayer, APPROVER1 mainnet creds,
# MPC_PUBLIC_KEY).
#
# Extra env (only for this command):
#   PARENT          mainnet vault owner, logged into outlayer-cli (NOT an approver)
#   APPROVER1       approver NEAR account with creds in ~/.near-credentials/mainnet
#   MPC_PUBLIC_KEY  bls12381g2:base58 (for `outlayer vault init`)
#   CONTRACT_ID     default outlayer.near
#   M_SWAP_TOKEN_IN / M_SWAP_TOKEN_OUT  defuse assets (default wrap.near → USDC)
#   M_SWAP_AMOUNT_IN amount_in minimal units (default 0.001 wNEAR)
# ============================================================================
cmd_multisig() {
    require_confidential_enabled            # ONECLICK_CONFIDENTIAL_JWT gate (SKIP if unset)
    check_coordinator

    # Confidential is mainnet-only — the testnet coordinator 503s these routes.
    if [ "$NETWORK" != "mainnet" ]; then
        echo -e "${YELLOW}SKIP:${NC} confidential multisig is mainnet-only (NETWORK=$NETWORK). Re-run with NETWORK=mainnet."
        exit 0
    fi

    local CONTRACT_ID="${CONTRACT_ID:-outlayer.near}"
    local APPROVER1="${APPROVER1:-}"
    local CREDS_DIR="$HOME/.near-credentials/$NETWORK"
    local SCRIPT_DIR; SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local RECOVERY_BIN="$SCRIPT_DIR/../scripts/customer-recovery/target/release/customer-recovery"

    # SKIP cleanly when the multisig bootstrap prerequisites are absent.
    local miss=()
    [ -n "${PARENT:-}" ] || miss+=("PARENT (mainnet vault owner logged into outlayer)")
    [ -n "${MPC_PUBLIC_KEY:-}" ] || miss+=("MPC_PUBLIC_KEY (for 'outlayer vault init')")
    [ -n "$APPROVER1" ] || miss+=("APPROVER1 (approver NEAR account)")
    [ -n "$APPROVER1" ] && [ ! -f "$CREDS_DIR/$APPROVER1.json" ] && miss+=("creds $CREDS_DIR/$APPROVER1.json")
    for t in jq curl outlayer near python3; do command -v "$t" >/dev/null || miss+=("tool: $t"); done
    if [ "${#miss[@]}" -gt 0 ]; then
        echo -e "${YELLOW}SKIP:${NC} confidential multisig needs an on-chain policy + approver signatures; missing:"
        for m in "${miss[@]}"; do echo "      - $m"; done
        echo "      (gate ONECLICK_CONFIDENTIAL_JWT is set, but the multisig infra is incomplete — skipping cleanly)"
        exit 0
    fi
    [ -f "$CREDS_DIR/$PARENT.json" ] || { echo -e "${RED}creds missing: $CREDS_DIR/$PARENT.json${NC}"; exit 1; }

    local M_TOKEN_IN="${M_SWAP_TOKEN_IN:-nep141:wrap.near}"
    # Native USDC on NEAR (Circle) — the coordinator's own canonical stablecoin asset id.
    local M_TOKEN_OUT="${M_SWAP_TOKEN_OUT:-nep141:17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1}"
    local M_AMOUNT_IN="${M_SWAP_AMOUNT_IN:-1000000000000000000000}" # 0.001 wNEAR (24 dec) — tiny

    echo -e "${CYAN}== Confidential MULTISIG (mainnet): pending_approval → approve → leaves pending_approval ==${NC}"

    local PARENT_PRIVKEY; PARENT_PRIVKEY=$(jq -r '.private_key' "$CREDS_DIR/$PARENT.json")
    # Without this, `outlayer` follows ~/.outlayer/default-network, which need not
    # be the network this run targets — the check would compare the wrong account.
    export OUTLAYER_NETWORK="$NETWORK"
    local WHOAMI; WHOAMI=$(outlayer whoami 2>/dev/null | awk -F': *' '/^Account:/{print $2; exit}')
    [ "$WHOAMI" = "$PARENT" ] || { echo -e "${RED}outlayer logged in as '$WHOAMI', not PARENT='$PARENT'${NC}"; exit 1; }

    echo -e "${CYAN}[build] customer-recovery (sign-nep413 + sign-bearer-near)…${NC}"
    (cd "$SCRIPT_DIR/../scripts/customer-recovery" && cargo build --release --quiet) || { echo -e "${RED}customer-recovery build failed${NC}"; exit 1; }

    # near CLI sometimes needs a TTY for the keychain signer — wrap via `script` if available.
    near_tty() {
        # `-t 1` as well as the binary: without a terminal `script` dies with
    # `tcgetattr/ioctl: Operation not supported on socket` and takes the step
    # with it — which surfaces as whatever that step was called, not as a
    # missing terminal. Guarded this way in the other copies of this helper.
    if command -v script >/dev/null 2>&1 && [ -t 1 ]; then
            local tmp; tmp=$(mktemp -t conf_cmd.XXXXXX.sh)
            printf 'set -euo pipefail\n%s\n' "$*" > "$tmp"
            script -q /dev/null bash "$tmp"; local rc=$?; rm -f "$tmp"; return $rc
        else eval "$@"; fi
    }

    # ─── vault (reuse VAULT_ID if provided, else deploy a fresh one) ───────────
    local VAULT_ID="${VAULT_ID:-}"
    if [ -z "$VAULT_ID" ]; then
        local VAULT_NAME="confms-$(date +%s)"
        VAULT_ID="$VAULT_NAME.$PARENT"
        echo -e "${CYAN}[vault] deploy $VAULT_ID…${NC}"
        local INIT_RC=0 INIT_OUT
        INIT_OUT=$(outlayer vault init --name "$VAULT_NAME" --exit-window 60s 2>&1) || INIT_RC=$?
        if [ $INIT_RC -ne 0 ] && echo "$INIT_OUT" | grep -q "outlayer vault resume"; then
            for _ in 1 2 3 4 5; do sleep 6; if outlayer vault resume "$VAULT_ID" >&2; then INIT_RC=0; break; fi; done
        fi
        [ $INIT_RC -eq 0 ] || { echo -e "${RED}vault init failed: $INIT_OUT${NC}"; exit 1; }
    else
        echo -e "${CYAN}[vault] reusing $VAULT_ID${NC}"
    fi
    echo -e "  vault: ${GREEN}$VAULT_ID${NC}"

    # ─── auth + policy helpers (mirror unified_op_e2e.sh) ──────────────────────
    mk_token() { CUSTOMER_RECOVERY_PRIVATE_KEY="$PARENT_PRIVKEY" "$RECOVERY_BIN" sign-bearer-near --account-id "$PARENT" --seed "$1" --vault-id "$VAULT_ID"; }
    AUTHH() { echo "Authorization: Bearer near:$(mk_token "$1")"; }

    local SEED="confms-$(date +%s)"
    local addr_resp WID
    addr_resp=$(curl -sS -G "$COORDINATOR_URL/wallet/v1/address" --data-urlencode "chain=near" -H "$(AUTHH "$SEED")")
    WID=$(echo "$addr_resp" | jq -r '.wallet_id // empty')
    [ -n "$WID" ] || { echo -e "${RED}address derive failed: $addr_resp${NC}"; exit 1; }
    echo -e "  sub-wallet: ${GREEN}$WID${NC} (addr $(echo "$addr_resp" | jq -r '.address'))"

    local A1_PRIV A1_PUB
    A1_PRIV=$(jq -r .private_key "$CREDS_DIR/$APPROVER1.json"); A1_PUB=$(jq -r .public_key "$CREDS_DIR/$APPROVER1.json")

    # store_policy: encrypt → sign → on-chain store_wallet_policy (exact unified_op_e2e.sh dance).
    echo -e "${CYAN}[policy] store multisig policy (threshold=1, capabilities.confidential.allowed=true)…${NC}"
    local POL enc encb64 sg sig_hex pub_hex store_args body
    POL=$(jq -nc --arg a "$APPROVER1" --arg ap "$A1_PUB" \
        '{rules:{transaction_types:["confidential"]}, capabilities:{confidential:{allowed:true}}, approval:{threshold:{required:1}, approvers:[{id:$a,pubkey:$ap}]}}')
    body=$(jq -nc --arg wid "$WID" --argjson p "$POL" '$p + {wallet_id:$wid}')
    enc=$(curl -sS -X POST "$COORDINATOR_URL/wallet/v1/encrypt-policy" -H "$(AUTHH "$SEED")" -H 'Content-Type: application/json' -d "$body")
    encb64=$(echo "$enc" | jq -r '.encrypted_base64 // empty'); [ -n "$encb64" ] || { echo -e "${RED}encrypt-policy failed: $enc${NC}"; exit 1; }
    # `caller` is SIGNED: the answer is good only for the account that sends the
    # store below, which is $PARENT here.
    sg=$(curl -sS -X POST "$COORDINATOR_URL/wallet/v1/sign-policy" -H "$(AUTHH "$SEED")" -H 'Content-Type: application/json' -d "$(jq -nc --arg ed "$encb64" --arg c "$PARENT" '{encrypted_data:$ed, caller:$c}')")
    sig_hex=$(echo "$sg" | jq -r '.signature_hex // empty'); pub_hex=$(echo "$sg" | jq -r '.public_key_hex // empty')
    [ -n "$sig_hex" ] || { echo -e "${RED}sign-policy failed: $sg${NC}"; exit 1; }
    store_args=$(jq -nc --arg pk "ed25519:$pub_hex" --arg ed "$encb64" --arg sg "$sig_hex" '{wallet_pubkey:$pk, encrypted_data:$ed, wallet_signature:$sg}')
    near_tty "near contract call-function as-transaction $CONTRACT_ID store_wallet_policy json-args '$store_args' prepaid-gas '100.0 Tgas' attached-deposit '0.1 NEAR' sign-as $PARENT network-config $NETWORK sign-with-keychain send" || { echo -e "${RED}store_wallet_policy failed${NC}"; exit 1; }
    sleep 5
    echo -e "  ${GREEN}policy stored${NC}"

    # vote helper: identical binding to T9/T10 — fetch wallet_pubkey from the approval,
    # sign NEP-413 `{vote}:{approval_id}:{wallet_pubkey}:{request_hash}`, POST it.
    vote() {
        local v=$1 aid=$2 h=$3 priv=$4 pub=$5 acct=$6 nonce sj sig wpk
        wpk=$(curl -sS "$COORDINATOR_URL/wallet/v1/approval/$aid" | jq -r '.wallet_pubkey // empty')
        nonce=$(head -c 32 /dev/urandom | base64 | tr -d '\n')
        sj=$(CUSTOMER_RECOVERY_PRIVATE_KEY="$priv" "$RECOVERY_BIN" sign-nep413 --message "$v:$aid:$wpk:$h" --recipient "$CONTRACT_ID" --nonce-base64 "$nonce")
        sig=$(echo "$sj" | jq -r '.signature')
        curl -sS -o /tmp/conf_vote.body -w '%{http_code}' -X POST "$COORDINATOR_URL/wallet/v1/$v/$aid" -H 'Content-Type: application/json' \
            -d "$(jq -nc --arg s "$sig" --arg pk "$pub" --arg ac "$acct" --arg nc "$nonce" '{signature:$s,public_key:$pk,account_id:$ac,nonce:$nc}')"
    }
    rstatus() { curl -sS "$COORDINATOR_URL/wallet/v1/requests/$1" -H "$(AUTHH "$SEED")" | jq -r '.status // empty'; }

    local PASS=0 FAILED=0
    mpass() { echo -e "  ${GREEN}PASS${NC} $*"; PASS=$((PASS+1)); }
    mfail() { echo -e "  ${RED}FAIL${NC} $*"; FAILED=$((FAILED+1)); }

    # ── 1: Trusted confidential swap on a multisig wallet → pending_approval ──
    echo -e "${CYAN}[1/3] confidential swap on a multisig wallet → expect pending_approval (NOT executed/rejected)…${NC}"
    local swap_body http body2 ST AID RID RH
    swap_body=$(jq -nc --arg ti "$M_TOKEN_IN" --arg to "$M_TOKEN_OUT" --arg ai "$M_AMOUNT_IN" '{token_in:$ti, token_out:$to, amount_in:$ai, min_amount_out:"1"}')
    http=$(curl -sS -o /tmp/conf_ms.body -w '%{http_code}' -X POST "$COORDINATOR_URL/wallet/v1/confidential/swap" -H "$(AUTHH "$SEED")" -H 'Content-Type: application/json' -d "$swap_body")
    body2=$(cat /tmp/conf_ms.body)
    if [ "$http" = "503" ]; then echo -e "  ${RED}503 confidential_unavailable${NC} — coordinator not configured for confidential intents (ENABLE_CONFIDENTIAL_INTENTS + upstream). $(echo "$body2" | jq -c . 2>/dev/null || echo "$body2")"; exit 1; fi
    ST=$(echo "$body2" | jq -r '.status // empty'); AID=$(echo "$body2" | jq -r '.approval_id // empty')
    RID=$(echo "$body2" | jq -r '.request_id // empty'); RH=$(echo "$body2" | jq -r '.request_hash // empty')
    if [ "$http" = "200" ] && [ "$ST" = "pending_approval" ] && [ -n "$AID" ] && [ -n "$RH" ]; then
        mpass "confidential swap → pending_approval (approval_id=$AID, request_hash present) — multisig path reached, NOT rejected as 'no multisig support'"
    else
        mfail "confidential swap MUST return pending_approval+approval_id+request_hash, got HTTP $http status='$ST': $(echo "$body2" | head -c200)"
    fi

    # ── 2: sign+submit the approver YES over the API-provided request_hash (threshold=1) ──
    if [ -n "$AID" ] && [ -n "$RH" ]; then
        echo -e "${CYAN}[2/3] approver YES vote over approve:$AID:<wallet_pubkey>:$RH …${NC}"
        local APPROVAL_H C
        APPROVAL_H=$(curl -sS "$COORDINATOR_URL/wallet/v1/approval/$AID" | jq -r '.request_hash // empty')
        [ "$APPROVAL_H" = "$RH" ] && mpass "approval.request_hash matches the swap response request_hash" \
            || echo -e "  ${YELLOW}note${NC} approval.request_hash='$APPROVAL_H' vs response='$RH' (signing the API-provided RH)"
        C=$(vote approve "$AID" "$RH" "$A1_PRIV" "$A1_PUB" "$APPROVER1")
        echo -e "  /approve HTTP $C: $(cat /tmp/conf_vote.body | head -c160)"
        [ "$C" = "200" ] && mpass "approver YES accepted (HTTP 200) over the confidential request_hash" \
            || mfail "/approve should accept the approver vote, got HTTP $C: $(cat /tmp/conf_vote.body | head -c160)"

        # ── 3: after threshold the request MUST leave pending_approval (control-flow assertion) ──
        echo -e "${CYAN}[3/3] poll: request must LEAVE pending_approval after the threshold…${NC}"
        local S=""; for _ in $(seq 1 20); do sleep 3; S=$(rstatus "$RID"); [ "$S" != "pending_approval" ] && [ -n "$S" ] && break; done
        case "$S" in
            processing|success|pending_deposit)
                mpass "confidential swap proceeded PAST pending_approval after threshold (status=$S) — keystore signed the approved confidential artifact" ;;
            failed|refunded)
                echo -e "  ${YELLOW}WARN${NC} left pending_approval then terminal '$S' downstream — control flow OK (approval→execute reached); terminal failure is mainnet liquidity/quote/unfunded-confidential-balance, NOT the multisig gate"
                mpass "confidential swap left pending_approval after threshold (reached execution; downstream-$S)" ;;
            pending_approval)
                mfail "confidential swap STUCK at pending_approval after a valid threshold-meeting approval — execution was NOT dispatched" ;;
            *)
                echo -e "  ${YELLOW}note${NC} post-approval status inconclusive (status='$S')"
                mpass "confidential swap left pending_approval after threshold (status='$S' != pending_approval)" ;;
        esac
    fi

    echo ""
    if [ "$FAILED" -gt 0 ]; then echo -e "${RED}MULTISIG: $FAILED failed, $PASS passed${NC}"; exit 1; fi
    echo -e "${GREEN}MULTISIG: all $PASS confidential-multisig checks passed${NC}"
    echo -e "${YELLOW}Cleanup (optional): $VAULT_ID holds locked NEAR + a per-wallet policy storage stake.${NC}"
}

# ============================================================================
# Dispatch
# ============================================================================

CMD="${1:-}"; shift || true
case "$CMD" in
    setup)          cmd_setup ;;
    roundtrip)      cmd_roundtrip ;;
    shield)         cmd_shield ;;
    unshield)       cmd_unshield ;;
    balance)        cmd_balance ;;
    deposit-intent) cmd_deposit_intent ;;
    withdraw)       cmd_withdraw ;;
    multisig)       cmd_multisig ;;
    status)         cmd_status "$@" ;;
    show)           cmd_show ;;
    reset)          cmd_reset ;;
    *)
        echo "Usage: $0 <command>"
        echo ""
        echo "  setup           — register/reuse wallet, show address + prerequisites"
        echo "  roundtrip       — SHIELD→UNSHIELD with balance assertions (the real-token test)"
        echo "  shield          — SHIELD 0.01 wNEAR (asserts settlement)"
        echo "  unshield        — UNSHIELD back (asserts settlement)"
        echo "  balance         — show confidential balances"
        echo "  deposit-intent  — cross-chain DEPOSIT quote (returns a bridge deposit address)"
        echo "  withdraw        — cross-chain WITHDRAW (needs WITHDRAW_TO; chain=near is rejected)"
        echo "  multisig        — MAINNET: confidential Trusted op under multisig → pending_approval →"
        echo "                    approve (NEP-413 vote) → asserts it LEAVES pending_approval (T9 analog)"
        echo "  status <id>     — poll a request to terminal status"
        echo "  show / reset    — print / delete saved wallet state"
        echo ""
        echo "GATE: live phases require ONECLICK_CONFIDENTIAL_JWT set; unset → SKIP (exit 0)."
        echo "PREREQ (roundtrip/shield): SHIELD_TOKEN already in your PUBLIC intents balance."
        echo "multisig also needs (else SKIP): NETWORK=mainnet, PARENT logged into outlayer,"
        echo "  APPROVER1 mainnet creds in ~/.near-credentials/mainnet, MPC_PUBLIC_KEY."
        ;;
esac
