//! WASI Preview 1 (P1) compiler
//!
//! Compiles Rust code to wasm32-wasip1 or wasm32-wasi targets using:
//! - cargo build --release --target wasm32-wasip1
//! - wasm-opt for size optimization

use anyhow::Result;
use bollard::Docker;
use tracing::info;

use super::docker;

/// The script the compiler runs inside the container.
///
/// Split out so it can be checked: it is shell generated by `format!`, it
/// only ever runs on a remote docker daemon, and a syntax error in it would
/// first be seen by a user whose build failed for no reason they could read.
fn compile_script(build_target: &str) -> String {
    format!(
        r#"
set -ex
cd /workspace

# Track compilation time
START_TIME=$(date +%s)

# Setup Rust environment
if [ -f /usr/local/cargo/env ]; then
    . /usr/local/cargo/env
elif [ -f $HOME/.cargo/env ]; then
    . $HOME/.cargo/env
fi

# Add WASM target
# Note: wasm32-wasi will be deprecated in Rust 1.84 (Jan 2025)
# Prefer wasm32-wasip1 for forward compatibility
TARGET_TO_ADD={build_target}
if [ "{build_target}" = "wasm32-wasi" ]; then
    # Try wasip1 first (Rust 1.78+), fallback to wasi
    if rustup target list | grep -q wasm32-wasip1; then
        TARGET_TO_ADD="wasm32-wasip1"
        echo "ℹ️  Using wasm32-wasip1 (recommended for Rust 1.78+)"
    fi
fi
rustup target add $TARGET_TO_ADD
echo "🔧 TARGET_TO_ADD: $TARGET_TO_ADD"

# Clone repository. Quote so the env values can't word-split into git options,
# and `--` on clone stops the URL being read as a flag. Inputs are also validated
# host-side (compiler/mod.rs) before reaching this script. (checkout takes a ref,
# not a pathspec, so it is quoted but NOT given `--`.)
git clone -- "$REPO" repo
cd repo
git checkout "$COMMIT"

# Hold the project to its own lock file. Without one, cargo resolves
# dependencies against whatever crates.io offers at build time, so the same
# commit compiles to different bytes on different days and a secret locked to a
# build stops opening for a project nobody touched. A project with no lock still
# builds: refusing it would break projects that run today, and the cost is
# liveness, not safety.
# Build WASM with size optimizations
build_wasm() {{
    if [ ! -f Cargo.lock ]; then
        echo "WARNING: no Cargo.lock — dependency versions are chosen at build time, so this commit will not compile to the same bytes on a later day"
        cargo build --release --target $TARGET_TO_ADD
        return $?
    fi
    # Held to the lock, so the resolution is part of the commit rather than of
    # the day. A lock that no longer matches Cargo.toml would make cargo refuse,
    # and a project that builds today must keep building — so that one case
    # falls back and says what it cost. Only that case: any other failure is the
    # project's, and rebuilding it would double the wait for nothing.
    if cargo build --release --target $TARGET_TO_ADD --locked 2>/tmp/build.err; then
        cat /tmp/build.err >&2
        return 0
    fi
    cat /tmp/build.err >&2
    if grep -q "needs to be updated" /tmp/build.err; then
        echo "WARNING: Cargo.lock does not match Cargo.toml, so dependency versions were resolved afresh. This commit will not compile to the same bytes on a later day — run cargo build locally and commit the updated Cargo.lock."
        cargo build --release --target $TARGET_TO_ADD
        return $?
    fi
    return 1
}}
build_wasm
# Sorted: directory order is whatever the filesystem returns, so a project that
# builds several binaries would otherwise have one picked at random — a
# different one on a rebuild, and the attested hash moving with it.
WASM_FILE=$(find target/$TARGET_TO_ADD/release -maxdepth 1 -name "*.wasm" -type f | sort | head -1)
WASM_COUNT=$(find target/$TARGET_TO_ADD/release -maxdepth 1 -name "*.wasm" -type f | wc -l)
if [ "$WASM_COUNT" -gt 1 ]; then
    echo "WARNING: $WASM_COUNT wasm binaries built; running the first by name: $WASM_FILE"
fi

# Find compiled WASM
if [ -z "$WASM_FILE" ]; then
    echo "❌ ERROR: No WASM file found!"
    find target/$TARGET_TO_ADD/release -type f
    exit 1
fi

echo "📦 Original WASM: $WASM_FILE"
ls -lah "$WASM_FILE"

# Copy to output
mkdir -p /workspace/output
cp "$WASM_FILE" /workspace/output/output.wasm

# Optimize WASM module with wasm-opt
ORIGINAL_SIZE=$(stat -c%s /workspace/output/output.wasm 2>/dev/null || stat -f%z /workspace/output/output.wasm)

echo "🔧 Optimizing WASM module with wasm-opt..."

# wasm-opt has to come from the image, not from the network. Installing it here
# would pull whatever version the distribution serves that day, and a different
# optimizer rewrites the module differently — the same source would compile to a
# different hash with nothing in the commit having changed.
if ! command -v wasm-opt &> /dev/null; then
    echo "ERROR: wasm-opt is missing from the compiler image. It is part of what decides the compiled bytes, so it cannot be fetched at build time."
    exit 1
fi

# Apply optimizations as per cargo-wasi:
# -Oz: optimize aggressively for size
# --strip-dwarf: remove DWARF debug info
# --strip-producers: remove producers section
# --enable-sign-ext: enable sign extension operations
# --enable-bulk-memory: enable bulk memory operations
wasm-opt -Oz \
    --strip-dwarf \
    --strip-producers \
    --enable-sign-ext \
    --enable-bulk-memory \
    /workspace/output/output.wasm \
    -o /workspace/output/output_optimized.wasm

mv /workspace/output/output_optimized.wasm /workspace/output/output.wasm
OPTIMIZED_SIZE=$(stat -c%s /workspace/output/output.wasm 2>/dev/null || stat -f%z /workspace/output/output.wasm)
SAVED=$((ORIGINAL_SIZE - OPTIMIZED_SIZE))
PERCENT=$((SAVED * 100 / ORIGINAL_SIZE))
echo "✅ Module optimization complete: $ORIGINAL_SIZE bytes → $OPTIMIZED_SIZE bytes (saved $SAVED bytes / $PERCENT%)"

ls -lah /workspace/output/output.wasm

# Calculate total compilation time
END_TIME=$(date +%s)
COMPILE_TIME=$((END_TIME - START_TIME))
echo "⏱️  Total compilation time: $COMPILE_TIME seconds"
"#
    )
}

/// Compile WASM for WASI Preview 1 target
///
/// This function:
/// 1. Clones the repository
/// 2. Installs wasm32-wasip1 (or wasm32-wasi) target
/// 3. Builds with cargo
/// 4. Optimizes with wasm-opt (-Oz, strip DWARF)
///
/// # Arguments
/// * `docker` - Docker client
/// * `container_id` - Container ID where compilation happens
/// * `build_target` - Build target (wasm32-wasip1 or wasm32-wasi)
///
/// # Returns
/// * `Ok(Vec<u8>)` - Compiled and optimized WASM bytes
/// * `Err(_)` - Compilation failed
pub async fn compile(docker: &Docker, container_id: &str, build_target: &str) -> Result<Vec<u8>> {
    info!("Compiling WASI Preview 1 module: target={}", build_target);
    let start_time = std::time::Instant::now();

    let compile_script = compile_script(build_target);

    // Execute compilation in container
    docker::exec_in_container(docker, container_id, &compile_script).await?;

    // Extract WASM file from container
    let wasm_bytes = docker::extract_wasm(docker, container_id, "/workspace/output/output.wasm").await?;

    let elapsed = start_time.elapsed();
    info!(
        "✅ WASI P1 compilation successful: WASM size={} bytes, total_time={:.2}s",
        wasm_bytes.len(),
        elapsed.as_secs_f64()
    );

    Ok(wasm_bytes)
}

/// The compile script is shell, generated by `format!`, and it runs on a remote
/// docker daemon. Nothing else in the build would catch a stray brace or an
/// unbalanced `if` in it — the first sign would be somebody's project failing
/// to compile with a message about a syntax error in a script they never wrote.
#[cfg(test)]
mod the_generated_shell_is_shell {
    use super::*;
    use std::io::Write;
    use std::process::{Command, Stdio};

    fn check(script: &str) {
        let mut child = Command::new("sh")
            .arg("-n")
            .stdin(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("sh must be available");
        child
            .stdin
            .as_mut()
            .unwrap()
            .write_all(script.as_bytes())
            .unwrap();
        let out = child.wait_with_output().unwrap();
        assert!(
            out.status.success(),
            "the generated script is not valid shell: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    #[test]
    fn every_target_the_p1_compiler_accepts_produces_valid_shell() {
        for target in ["wasm32-wasip1", "wasm32-wasi"] {
            check(&compile_script(target));
        }
    }

    #[test]
    fn the_p1_script_holds_the_project_to_its_lock_file() {
        let script = compile_script("wasm32-wasip1");
        assert!(
            script.contains("--locked"),
            "without it the same commit resolves different dependencies on different days"
        );
        assert!(
            script.contains("needs to be updated"),
            "a lock that no longer matches must fall back rather than refuse a project that builds today"
        );
    }

    #[test]
    fn the_p1_script_chooses_the_binary_by_name() {
        let script = compile_script("wasm32-wasip1");
        assert!(
            script.contains("| sort | head -1"),
            "an unsorted pick makes the attested hash a property of the filesystem"
        );
    }

    #[test]
    fn the_p1_script_will_not_fetch_its_optimiser() {
        let script = compile_script("wasm32-wasip1");
        assert!(
            !script.contains("apt-get install -y -qq binaryen"),
            "installing wasm-opt at build time makes the optimiser, and so the hash, a function of the day"
        );
    }
}

