//! WASI Preview 2 (P2) compiler
//!
//! Compiles Rust code to wasm32-wasip2 target using:
//! - cargo build --release --target wasm32-wasip2
//! - wasm-tools strip for optimization

use anyhow::Result;
use bollard::Docker;
use tracing::info;

use super::docker;

/// The script the compiler runs inside the container.
///
/// Split out so it can be checked: it is shell generated by `format!`, it
/// only ever runs on a remote docker daemon, and a syntax error in it would
/// first be seen by a user whose build failed for no reason they could read.
fn compile_script() -> String {
    format!(
        r#"
set -ex
cd /workspace

# Track compilation time
START_TIME=$(date +%s)

# Setup Rust environment
if [ -f /usr/local/cargo/env ]; then
    . /usr/local/cargo/env
elif [ -f $HOME/.cargo/env ]; then
    . $HOME/.cargo/env
fi

# Add WASM target for WASI Preview 2
echo "ℹ️  Using wasm32-wasip2 (WASI Preview 2)"
rustup target add wasm32-wasip2
echo "🔧 TARGET: wasm32-wasip2"

# Clone repository. Quote so the env values can't word-split into git options,
# and `--` on clone stops the URL being read as a flag. Inputs are also validated
# host-side (compiler/mod.rs) before reaching this script. (checkout takes a ref,
# not a pathspec, so it is quoted but NOT given `--`.)
git clone -- "$REPO" repo
cd repo
git checkout "$COMMIT"

# Build WASM component with cargo. Held to the project's own lock file where
# there is one — see the note in the P1 compiler for why, and for why a lock
# that no longer matches falls back instead of refusing.
build_wasm() {{
    if [ ! -f Cargo.lock ]; then
        echo "WARNING: no Cargo.lock — dependency versions are chosen at build time, so this commit will not compile to the same bytes on a later day"
        cargo build --release --target wasm32-wasip2
        return $?
    fi
    if cargo build --release --target wasm32-wasip2 --locked 2>/tmp/build.err; then
        cat /tmp/build.err >&2
        return 0
    fi
    cat /tmp/build.err >&2
    if grep -q "needs to be updated" /tmp/build.err; then
        echo "WARNING: Cargo.lock does not match Cargo.toml, so dependency versions were resolved afresh. This commit will not compile to the same bytes on a later day — run cargo build locally and commit the updated Cargo.lock."
        cargo build --release --target wasm32-wasip2
        return $?
    fi
    return 1
}}
build_wasm
# Sorted, so several binaries do not mean a random one.
WASM_FILE=$(find target/wasm32-wasip2/release -maxdepth 1 -name "*.wasm" -type f | sort | head -1)
WASM_COUNT=$(find target/wasm32-wasip2/release -maxdepth 1 -name "*.wasm" -type f | wc -l)
if [ "$WASM_COUNT" -gt 1 ]; then
    echo "WARNING: $WASM_COUNT wasm binaries built; running the first by name: $WASM_FILE"
fi

# Find compiled WASM
if [ -z "$WASM_FILE" ]; then
    echo "❌ ERROR: No WASM file found!"
    find target/wasm32-wasip2/release -type f
    exit 1
fi

echo "📦 Original WASM component: $WASM_FILE"
ls -lah "$WASM_FILE"

# Copy to output
mkdir -p /workspace/output
cp "$WASM_FILE" /workspace/output/output.wasm

# Optimize WASM P2 component
ORIGINAL_SIZE=$(stat -c%s /workspace/output/output.wasm 2>/dev/null || stat -f%z /workspace/output/output.wasm)

# WASI Preview 2: already a proper CLI component from cargo
# Just strip debug info and optimize
# Stripping is not optional: a component that skipped it is a different binary
# with a different hash, and the skip would be silent.
if ! command -v wasm-tools &> /dev/null; then
    echo "ERROR: wasm-tools is missing from the compiler image. Stripping decides the compiled bytes, so a build without it is not the build this platform promises."
    exit 1
fi

echo "🔧 Optimizing WASI P2 CLI component..."

# Strip debug information from component
wasm-tools strip /workspace/output/output.wasm -o /workspace/output/output_optimized.wasm
mv /workspace/output/output_optimized.wasm /workspace/output/output.wasm

OPTIMIZED_SIZE=$(stat -c%s /workspace/output/output.wasm 2>/dev/null || stat -f%z /workspace/output/output.wasm)
SAVED=$((ORIGINAL_SIZE - OPTIMIZED_SIZE))
PERCENT=$((SAVED * 100 / ORIGINAL_SIZE))
echo "✅ Component optimization complete: $ORIGINAL_SIZE bytes → $OPTIMIZED_SIZE bytes (saved $SAVED bytes / $PERCENT%)"

ls -lah /workspace/output/output.wasm

# Calculate total compilation time
END_TIME=$(date +%s)
COMPILE_TIME=$((END_TIME - START_TIME))
echo "⏱️  Total compilation time: $COMPILE_TIME seconds"
"#
    )
}

/// Compile WASM for WASI Preview 2 target
///
/// This function:
/// 1. Clones the repository
/// 2. Installs wasm32-wasip2 target
/// 3. Builds with cargo (produces CLI component)
/// 4. Strips debug info with wasm-tools
///
/// # Arguments
/// * `docker` - Docker client
/// * `container_id` - Container ID where compilation happens
/// * `build_target` - Build target (wasm32-wasip2)
///
/// # Returns
/// * `Ok(Vec<u8>)` - Compiled and optimized WASM component bytes
/// * `Err(_)` - Compilation failed
pub async fn compile(docker: &Docker, container_id: &str, build_target: &str) -> Result<Vec<u8>> {
    info!("Compiling WASI Preview 2 component: target={}", build_target);
    let start_time = std::time::Instant::now();

    let compile_script = compile_script();

    // Execute compilation in container
    docker::exec_in_container(docker, container_id, &compile_script).await?;

    // Extract WASM file from container
    let wasm_bytes = docker::extract_wasm(docker, container_id, "/workspace/output/output.wasm").await?;

    let elapsed = start_time.elapsed();
    info!(
        "✅ WASI P2 compilation successful: Component size={} bytes, total_time={:.2}s",
        wasm_bytes.len(),
        elapsed.as_secs_f64()
    );

    Ok(wasm_bytes)
}

/// See the note on the P1 compiler's tests: this script is generated shell that
/// only ever runs on a remote docker daemon.
#[cfg(test)]
mod the_generated_shell_is_shell {
    use super::*;
    use std::io::Write;
    use std::process::{Command, Stdio};

    #[test]
    fn the_p2_script_is_valid_shell() {
        let script = compile_script();
        let mut child = Command::new("sh")
            .arg("-n")
            .stdin(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("sh must be available");
        child.stdin.as_mut().unwrap().write_all(script.as_bytes()).unwrap();
        let out = child.wait_with_output().unwrap();
        assert!(
            out.status.success(),
            "the generated script is not valid shell: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    #[test]
    fn the_p2_script_never_ships_an_unstripped_component() {
        let script = compile_script();
        assert!(
            script.contains("--locked"),
            "without it the same commit resolves different dependencies on different days"
        );
        assert!(
            !script.contains("skipping WASI Preview 2 component optimization"),
            "a component that skipped stripping is a different binary with a different hash, and the skip was silent"
        );
        assert!(
            script.contains("| sort | head -1"),
            "an unsorted pick makes the attested hash a property of the filesystem"
        );
    }
}
